<script setup>

import { Button, DataTable, Column, Tag } from 'primevue';
import { ref } from 'vue';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head } from '@inertiajs/vue3';
import Container from '@/Components/containers/Container.vue';
import EditMusicApprovalModal from './music-approval-partials/EditMusicApprovalModal.vue';
import { storeToRefs } from 'pinia';
import { useMusicParamStore } from '@/Stores/musicParams';
import Paginator from '@/Components/Paginator.vue';
import SearchForm from '@/Components/forms/SearchForm.vue';

defineProps({
    musics: Object
})

const { params } = storeToRefs(useMusicParamStore());

</script>

<template>
    <Head title="Music Approval" />

    <AuthenticatedLayout>
        <template #header>
            Music Approval
        </template>

        <Container>
            <template #header>
                <SearchForm 
                    :params="params"
                    :url="route(route().current())"
                />
            </template>
            <template #body>
                <DataTable
                    :value="musics.data"
                    scrollable
                    scrollHeight="70vh"
                    :rows="5"
                    stripedRows
                    removableSort
                    resizable-columns
                    show-gridlines
                >
                    
                    <Column field="id" header="ID" sortable />
                    <Column field="title" header="Title" sortable />
                    <Column header="Creator" sortable>
                        <template #body="slotProps">
                            {{ slotProps.data.creator.first_name }} {{ slotProps.data.creator.last_name }}
                        </template>
                    </Column>
                    <Column field="generated_by" header="Generated By" sortable />

                    <Column field="generated_at" header="Generated At" sortable />
                    
                    <Column field="status" header="Status" sortable>
                        <template #body="slotProps">
                            <Tag
                                :value="slotProps.data.status.charAt(0).toUpperCase() + slotProps.data.status.slice(1)"
                                :severity="{
                                    'pending': 'info',
                                    'under review': 'warning',
                                    'approved': 'success',
                                    'rejected': 'danger'
                                }[slotProps.data.status]"
                            />
                        </template>
                    </Column>
                    <Column header="Review Comments" sortable >
                        <template #body="slotProps">
                            <div class="w-[200px]">
                                {{ slotProps.data.review_comments || 'N/A' }}
                            </div>
                        </template>
                    </Column>

                    <Column field="action" header="Action" frozen align-frozen="right" v-if="route().current().includes('music-approval')">
                        <template #body="slotProps">
                            <div class="flex flex-col gap-2">
                                <EditMusicApprovalModal :music="slotProps.data" />
                            </div>
                        </template>
                    </Column>

                </DataTable>

                <div class="mt-2" v-if="musics?.links?.length > 3">
                    <Paginator 
                        :params="params"
                        :links="musics.links"
                    />
                </div>
            </template>
        </Container>
    </AuthenticatedLayout>
</template>