<script setup>
import Container from '@/Components/containers/Container.vue'
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue'
import { Head } from '@inertiajs/vue3'
import { useAudioStore } from '@/Stores/audio'

const props = defineProps({ 
    musics: Object 
})

const audioStore = useAudioStore()

const playSong = (music) => {
    audioStore.playSong(music)
}
</script>

<template>
    <Head title="Explore Music" />

    <AuthenticatedLayout>
        <template #header>
            <h2 class="font-semibold text-xl text-zinc-800 dark:text-zinc-200 leading-tight">Explore</h2>
        </template>

        <Container>
            <template #body>
                <div class="whitespace-pre-wrap">
                    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2 p-2">
                        <div 
                            v-for="(music, index) in musics.data" 
                            :key="index"
                            class="p-4 border dark:border-zinc-700 rounded-lg shadow hover:shadow-lg transition duration-300 bg-white dark:bg-zinc-800"
                        >
                            <h3 class="text-lg font-semibold mb-2">{{ music.title }}</h3>
                            <p class="text-sm text-zinc-600 dark:text-zinc-400 mb-1">Generated by: {{ music.generated_by }}</p>
                            <p class="text-sm text-zinc-600 dark:text-zinc-400 mb-1">Generated at: {{ music.generated_at }}</p>
                            <p class="text-sm text-zinc-600 dark:text-zinc-400 mb-1">Description: {{ music.description }}</p>
                            <button 
                                class="mt-2 px-4 py-2 bg-green-600 text-white rounded-full hover:bg-green-700 transition"
                                @click="playSong(music)"
                            >
                                Play
                            </button>
                        </div>
                    </div>
                </div>
            </template>
        </Container>
    </AuthenticatedLayout>
</template>