<script setup>
import { useAudioStore } from '@/Stores/audio';
import { storeToRefs } from 'pinia';


defineProps({
    musics: {
        type: Object,
        required: true
    }
})

const audioStore = useAudioStore()

const { currentSong } = storeToRefs(useAudioStore());

const playSong = (music) => {
    audioStore.playSong(music)
}

</script>

<template>
    <div 
        v-for="(music, index) in musics" 
        :key="index"
        class="p-4 border dark:border-neutral-700 rounded-lg shadow hover:shadow-lg transition duration-300 bg-white dark:bg-neutral-800"
    >
        <h3 class="text-lg font-semibold mb-2">{{ music.title }}</h3>
        <p class="text-sm text-neutral-600 dark:text-neutral-400 mb-1">Generated by: {{ music.generated_by }}</p>
        <p class="text-sm text-neutral-600 dark:text-neutral-400 mb-1">Generated at: {{ music.generated_at }}</p>
        <p class="text-sm text-neutral-600 dark:text-neutral-400 mb-1">Album: {{ music.album?.name }}</p>
        <p class="text-sm text-neutral-600 dark:text-neutral-400 mb-1">
            Creator: 
            <span>
                {{ music.creator?.first_name }}
                {{ music.creator?.last_name }}
            </span>
        </p>

        <button 
            class="mt-2 px-4 py-2 bg-green-600 text-white rounded-full hover:bg-green-700 transition"
            @click="playSong(music)"
        >
            <span v-if="currentSong && currentSong.id === music.id"> Playing</span>
            <span v-else> Play</span>
        </button>
    </div>
</template>