<script setup>
import { useAudioStore } from '@/Stores/audio';
import { storeToRefs } from 'pinia';
import { Button } from 'primevue';
import { router, Link } from '@inertiajs/vue3';
import AddToPlaylistModal from './music-card-partials/AddToPlaylistModal.vue';

defineProps({
    musics: {
        type: Object,
        required: true
    }
})

const audioStore = useAudioStore()
const { currentSong } = storeToRefs(useAudioStore());

const playSong = (music) => {
    audioStore.playSong(music)
}
</script>

<template>
    <div 
        v-for="(music, index) in musics" 
        :key="index"
        class="group p-4 sm:p-5 border dark:border-neutral-700 rounded-xl shadow-sm hover:shadow-xl transition-all duration-300 bg-white dark:bg-neutral-800"
    >
        <div class="flex flex-col sm:flex-row gap-4 sm:gap-0 sm:justify-between sm:items-center mb-5">
            <div class="flex-1">
                <h3 class="text-lg sm:text-xl font-bold text-neutral-800 dark:text-neutral-100 mb-1 line-clamp-1">
                    {{ music.title }}
                </h3>
                <p class="text-sm font-medium text-neutral-500 dark:text-neutral-400">
                    {{ music.creator?.first_name }} {{ music.creator?.last_name }}
                </p>
            </div>
            <Button 
                @click="playSong(music)"
                :class="[
                    'w-full sm:w-auto min-w-[100px]',
                    currentSong && currentSong.id === music.id 
                        ? 'p-button-success' 
                        : 'p-button-primary'
                ]"
                :icon="currentSong && currentSong.id === music.id ? 'ri-volume-up-line' : 'ri-play-fill'"
            >
                {{ currentSong && currentSong.id === music.id ? 'Playing' : 'Play' }}
            </Button>
        </div>

        <div class="grid grid-cols-1 sm:grid-cols-2 gap-2 mb-5">
            <div class="space-y-2">
                <p class="text-sm flex justify-between sm:block">
                    <span class="text-neutral-500 dark:text-neutral-400">Album:</span>
                    <span class="ml-0 sm:ml-2 font-medium text-neutral-700 dark:text-neutral-300">{{ music.album?.name }}</span>
                </p>
                <p class="text-sm flex justify-between sm:block">
                    <span class="text-neutral-500 dark:text-neutral-400">Generated by:</span>
                    <span class="ml-0 sm:ml-2 font-medium text-neutral-700 dark:text-neutral-300">{{ music.generated_by }}</span>
                </p>
            </div>
            <div class="text-left sm:text-right">
                <p class="text-sm text-neutral-500 dark:text-neutral-400 flex justify-between sm:block">
                    Generated at:
                    <span class="font-medium text-neutral-700 dark:text-neutral-300">{{ music.generated_at }}</span>
                </p>
            </div>
        </div>

        <div class="flex flex-col sm:flex-row gap-2 sm:gap-3 sm:justify-end border-t dark:border-neutral-700 pt-4">
            <AddToPlaylistModal v-if="$page.props.auth.user?.playlists && !route().current('playlist.*')" :musicId="music.id" />
            <Button
                severity="secondary"
                icon="ri-external-link-line"
                text
                as="a"
                :href="`/storage/${music.file_path}`"
                target="_blank" 
                rel="noopener noreferrer"
                class="w-full sm:w-auto hover:bg-neutral-100 dark:hover:bg-neutral-700"
            >
                Open
            </Button>
        </div>
    </div>
</template>